import type { CompareResult } from '../../types'

const COLOR = { met: '#16a34a', partial: '#d97706', missing: '#dc2626' }
const LABEL = { met: 'Met', partial: 'Partial', missing: 'Missing' }

function renderGroup(
  items: CompareResult['results'],
  status: 'met' | 'partial' | 'missing'
) {
  if (items.length === 0) return ''
  return `
    <div class="group">
      <p class="group-label" style="color:${COLOR[status]}">${LABEL[status]}</p>
      ${items.map(item => `
        <div class="item item--${status}">
          <p class="item-req">${item.requirement}</p>
          ${item.suggestion ? `<p class="item-suggestion">${item.suggestion}</p>` : ''}
        </div>
      `).join('')}
    </div>`
}

export function buildReportHTML(result: CompareResult, score: number, date: string) {
  const met     = result.results.filter(r => r.status === 'met')
  const partial = result.results.filter(r => r.status === 'partial')
  const missing = result.results.filter(r => r.status === 'missing')

  return `<!DOCTYPE html><html><head><meta charset="UTF-8">
    <title>GapCheck Report</title>
    <style>
      * { margin:0; padding:0; box-sizing:border-box; }
      body { font-family:system-ui,sans-serif; color:#111827; background:#fff; padding:48px; max-width:760px; margin:0 auto; }
      .header { display:flex; justify-content:space-between; padding-bottom:20px; border-bottom:2px solid #111827; margin-bottom:28px; }
      .brand { font-size:18px; font-weight:700; }
      .date  { font-size:12px; color:#6b7280; margin-top:4px; }
      .score-block { background:#f9fafb; border:1px solid #e5e7eb; border-radius:8px; padding:20px 24px; margin-bottom:32px; display:flex; justify-content:space-between; gap:24px; }
      .score-num { font-size:40px; font-weight:700; color:#1a3a5c; flex-shrink:0; }
      .score-summary { font-size:13px; color:#374151; line-height:1.6; }
      .score-legend { display:flex; gap:16px; margin-top:12px; font-size:12px; font-weight:600; }
      .group { margin-bottom:28px; }
      .group-label { font-size:11px; font-weight:700; text-transform:uppercase; letter-spacing:0.8px; margin-bottom:10px; }
      .item { border:1px solid #e5e7eb; border-left:3px solid; border-radius:6px; padding:12px 14px; margin-bottom:8px; }
      .item--met { border-left-color:#16a34a; }
      .item--partial { border-left-color:#d97706; }
      .item--missing { border-left-color:#dc2626; }
      .item-req { font-size:13px; color:#111827; line-height:1.4; }
      .item-suggestion { font-size:12px; color:#6b7280; margin-top:6px; padding:6px 8px; background:#f9fafb; border-radius:4px; }
      .footer { margin-top:40px; padding-top:16px; border-top:1px solid #e5e7eb; font-size:11px; color:#9ca3af; text-align:center; }
      @media print { .item { break-inside:avoid; } .group { break-inside:avoid; } }
    </style>
  </head><body>
    <div class="header">
      <div><div class="brand">GapCheck</div><div class="date">Report generated ${date}</div></div>
    </div>
    <div class="score-block">
      <div>
        <p class="score-summary">${result.overallSummary}</p>
        <div class="score-legend">
          <span style="color:#16a34a">Met: ${met.length}</span>
          <span style="color:#d97706">Partial: ${partial.length}</span>
          <span style="color:#dc2626">Missing: ${missing.length}</span>
        </div>
      </div>
      <div class="score-num">${score}%</div>
    </div>
    ${renderGroup(missing, 'missing')}
    ${renderGroup(partial, 'partial')}
    ${renderGroup(met, 'met')}
    <div class="footer">Generated by GapCheck</div>
  </body></html>`
}